### ISSUE TITLE
[BUG] instructions not complete or problem with websocket connection

### ISSUE THREAD

**Issue by Gabri** [SockTrader/SockTrader#11]
Very interesting project. I'd like to add some functionalities and work with it (I'm doing a bot with nodejs by my own, inspired by some on github). I found really interesting the part with tradingview chart connected with the trading system.
Anyway, before spend some time and developing, I'd like to see something.
I made a backtest as the examples [OK].
I run unit tests [OK].
I run the web-server as dev (as sudo because it needs root privileges to open ports below 1024).
Then I downloaded Dashboard project, run it, after some seconds it open a blank page with a top bar with title "SockTrader", and in the right part the status (X) and a button "Start". I found some errors on console, it seems it cannot connect via "WebSocket connection to 'ws://localhost:8080/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED" (the web-serve was live).
Maybe instructions are not complete to run it (?)
Is it possible to see the tradingview part if already working? (if you tell me the library used and the cost is not too much I'd like to try it buying the license)

Thanks

**Comment by cwouter** [comment]
Hi @Gabri,

I'm glad to hear that you're interested in our project. I really appreciate that! I guess you're probably trying to use the old dashboard from the [archived git repo](https://github.com/SockTrader/Dashboard). Well I've got some bad news, because we're not supporting that dashboard anymore. That dashboard was built using [react-stockcharts](https://github.com/rrag/react-stockcharts) but it was lacking a lot of features and so we decided to integrate the [TradingView library](https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/) in a different private closed source repository. But we left the dashboard online so that the community could pick it up if somebody wanted to. But the bugs that you encountered are normal since the SockTrader tradingbot itself has changed dramatically since then. (You can probably still make it work if you would revert to a previous commit in the git history of the master branch)

The [screenshot in our README](https://github.com/SockTrader/SockTrader#whats-the-purpose-of-the-webserver) is based on the fancy new closed source dashboard. We had to make it closed source, because of the license agreement of the TradingView library. That's the only reason..

**However...(the good news)**
We are currently working very hard on this frontend, and we are planning to release it as a static hosted website very soon. But we still have to add some extra configuration options so that you can hook up any SockTrader backend to the hosted dashboard. So that you don't have to run the dashboard by yourself.. and we can still be compliant with the TradingView license agreement. And hopefully we can attract some more contributors and users by releasing this dashboard.

**One more thing..**
So if you're working on your own tradingbot.. why not combining forces and work on the same project? We can both increase the development speed and add features which are mutually interesting. It would be very stupid to waste time by building the same features twice ;-). If you want we can talk about this on skype, slack or whatsapp. In any case we're open to any proposal..

By the way: the trading view library is completely free (but not open source). You just have to sign a few papers to get access to the github repository. But there is not license cost attached to it..

**Comment by Gabri** [comment]
Hi, thanks for your detailed reply.
I've tried a lot of bots out there. I found interesting ones above all in nodejs/typescript, but usually no one has attracted me to the point of starting to developing on it. I'd wanted some good features but not too heavy to run on a very simple vps (I'd like it could be run ideally also in a GCP always free Compute Engine, or the free AWS analogue), so I started writing it from scratch using a CLI interface (vorpal), attached ccxt, starting implementing Bitmex and Binance (my preferred exchanges for bot trading)...
I understand what you say and it's what I think too (why not combining forces and work on the same project?), it's a bit frustrating seeing people that write their own bot and usually no ones is ready for production ..when probably focusing with just few of them could potentially produce great bots.
In the end what I'm looking for is a simple and stable bot that could run some strategies (backtesting them) and managing open positions.
Ok, I'll take a deeper look to the project and ..we will see  :)

**Comment by Gabri** [comment]
Maybe it could be useful if in the README (maybe in section https://github.com/SockTrader/SockTrader#we-need-your-help) you will add some link to connect wit you (discord or telegram are maybe the more used for these kind of projects/community) and start making a community and interest on the project. Just a suggestion

**Comment by cwouter** [comment]
That's exactly what we are trying to build for v1.0 of SockTrader! We're aiming for a simple but well tested bot with a visual backtesting dashboard. But don't underestimate the amount of work you need to do before you get there. For now the backtesting engine works perfectly in "CLI mode".

Thx for the tip, i'll update the README file.
